@startuml
actor Parent
Parent --> (Inscrire enfant)
Parent --> (Consulter notes)
Parent --> (Consulter absences)
Parent --> (Inscrire activités)
Parent --> (Payer frais)
Parent --> (Consulter emploi)
Parent --> (Communiquer)
@enduml
